name: ipfs-crdt-shared-editing
version: master
summary: Decentralized Real-Time Collaborative Documents
description: |
  Decentralized Real-Time Collaborative Documents

confinement: strict
grade: devel

apps:
  ipfs-crdt-shared-editing:
    command: http-server -c-1 -p 1234 $SNAP/docs
    plugs: [network, network-bind]

parts:
  ipfs-crdt-shared-editing:
    source: https://github.com/vigzmv/IPFS-CRDT-shared-editing.git
    plugin: nodejs
    node-package-manager: yarn
    node-packages: [webpack, http-server]
    install: |
      webpack
      cp -R docs/ $SNAPCRAFT_PART_INSTALL
    build-packages: [g++, make]
